version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: /app
    docker:
      - image: docker:18.05.0-ce-git #https://hub.docker.com/r/library/docker/tags/
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce #required for multi stage builds

      - run:
          name: Install Docker Compose
          command: |
            apk add --no-cache 'py2-pip'
            pip install 'docker-compose==1.21.1'

      - run:
          name: Build Docker images
          command: |
            docker-compose build

      - run:
          name: Run Tests 
          command: |
            docker-compose up

      - run:
          name: Tag Docker image
          command: |
            docker tag chartjs-node-canvas $DOCKER_USER/chartjs-node-canvas:${CIRCLE_SHA1}

      - run:
          name: Push Docker image to Dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_USER/chartjs-node-canvas:${CIRCLE_SHA1}