version: 2
jobs:

  build:
    branches:
      only:
        # - master
        - docker-integration
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git #https://hub.docker.com/r/library/docker/tags/
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce #required for multi stage builds

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0 awscli==1.11.76

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: Build Docker images
          command: |
            docker-compose build --cache-from=app

      - run:
          name: Run Tests 
          command: |
            docker-compose up

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

      - run:
          name: Tag Docker image
          command: |
            docker tag chartjs-node-canvas $DOCKER_USER/chartjs-node-canvas:${CIRCLE_SHA1}

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      - run:
          name: Push Docker image to Dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_USER/chartjs-node-canvas:${CIRCLE_SHA1}

# workflows:
#   version: 2
#   build_test_push:
#     jobs:

#       - build

#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master

#       - push:
#           requires:
#             - test