name: Node CI

on: [push]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ['10.x', '11.x', '12.x', '13.x']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: Build
      run: npm run-script build
    - name: Lint
      run: npm run-script lint
    - name: Test
      run: npm run-script test
    - uses: codecov/codecov-action@v1
      with:
        name: Node v${{ matrix.node-version }}
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./reports/test-coverage/cobertura-coverage.xml
        fail_ci_if_error: true
    # Does not yet support wildcards! Needs v2: https://github.com/actions/upload-artifact/pull/54
    # When ready see https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifacts
    # - name: Package Artifact
    #   run: npm pack
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: Node v${{ matrix.node-version }}
    #     path: '*.tgz'
  publish:
    needs: build-and-test
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ['13.x']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: Build
      run: npm run-script build
    - name: Check Size
      run: npm run-script package-size
    - name: Publish
      shell: bash
      run: ./scripts/publish.sh
      env:
        CI: true
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}